name: dslink
version: 1.0.0
description: DSLink SDK for Dart
dependencies:
  args: ">=0.12.0 <0.14.0"
  bignum: '>=0.0.5 <0.1.0'
  cipher: '>=0.7.1 <1.0.0'
  logging: ">=0.9.0 <0.13.0"
  crypto: "^0.9.0"
  archive: "^1.0.20"
  http: "^0.11.3"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  browser: any
environment:
  sdk: ">=1.9.0-dev"
executables:
  dsbroker: broker
  dsbeacon: beacon
