name: dslink
version: 1.0.0
description: DSLink SDK for Dart
dependencies:
  args: ">=0.12.0 <0.14.0"
  bignum:
    # path: ../dart-bignum
    git: "git://github.com/IOT-DSA/dart-bignum"
  cipher:
    # path: ../cipher
    git: "git://github.com/IOT-DSA/cipher"
  logging: ">=0.9.0 <0.13.0"
  crypto: "^0.9.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  browser: any
environment:
  sdk: ">=1.9.0-dev"
executables:
  dsbroker: broker
  dsbeacon: beacon
