name: dslink
version: 1.0.0
description: DSLink SDK for Dart
dependencies:
  quiver: ">=0.21.0 <0.25.0"
  bignum: any
  cipher: ">=0.7.1"
dev_dependencies:
  scheduled_test: ">=0.11.6 <0.12.0"
  browser: any
environment:
  sdk: ">=1.9.0-dev"
