name: dslink
version: 0.6.1
description: "DSA IoT Platform - DSLink SDK for Dart"
homepage: "http://iot-dsa.org"
dependencies:
  args: "^0.13.4"
  bignum: "^0.1.0"
  cipher:
    git: https://github.com/IOT-DSA/cipher.git
  logging: "^0.11.3"
  crypto: "0.9.1"
  msgpack: "^0.7.1"
  json_diff: "^0.1.2"
authors:
  - Kenneth Endfinger <k.endfinger@dglogik.com>
  - Rick Zhou <z.zhou@dglogik.com>
  - Michael Bullington <m.bullington@dglogik.com>
  - Matthew Butler <m.butler@dglogik.com>
dev_dependencies:
  test: ">=0.12.13"
  dsbroker:
    git: "https://github.com/IOT-DSA/broker-dart.git"
  browser: "^0.10.0"
environment:
  sdk: ">=1.11.0"
executables:
  dsbeacon: beacon
