name: dslink
version: 1.0.0
description: DSLink SDK for Dart
dev_dependencies:
  linux:
    git: https://github.com/DirectMyFile/linux.git
  scheduled_test: ">=0.11.6 <0.12.0"
  grinder: ">=0.6.3 <0.7.0"